version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pmt_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pmt_backend
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pmt_backend"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: katamaric/pmt-backend:latest
    container_name: pmt_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pmt_backend
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    ports:
      - "8080:8080"

  frontend:
    image: katamaric/pmt-frontend:latest
    container_name: pmt_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  db_data:
