version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pmt_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pmt_backend
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: pmt_backend
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASS: password
    ports:
      - "8080:8080"

volumes:
  db_data:
